import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { headers } from "next/headers";
import { cache } from "react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const fetchTenantConfig = cache(async (host: string) => {
  // Simulate a short mock delay
  await new Promise((resolve) => setTimeout(resolve, 50));
  return {
    primaryColor: "#3b82f6",
    tenantName: "Mi Tienda Demo",
  };
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const host = headersList.get("host") || "localhost:3000";
  const config = await fetchTenantConfig(host);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <style
          dangerouslySetInnerHTML={{
            __html: `:root { --color-primary: ${config.primaryColor}; }`,
          }}
        />
        {children}
      </body>
    </html>
  );
}
